/**
 * Pure SEO / brand facts. NO React, env, or icon imports — this module is the
 * single source of truth for brand text and is safe to import from both the
 * app (routes, <head>) and the build-time SEO asset generator (scripts/).
 */

/** Default origin. Override per-environment with `VITE_SITE_URL`. */
export const DEFAULT_SITE_URL = "https://civicsins.gopalkhadka.com.np";

/** Social profiles (icons are attached in `site.ts`, which can import React). */
export const socialLinks = [
	{ label: "GitHub", href: "https://github.com/Gopal-Khadka/civic-sense" },
] as const;

export const seoConfig = {
	name: "Civic Sins",
	shortName: "Civic Sins",
	tagline: "You do this too.",
	description:
		"Short comics about the small public habits everyone hates and sometimes commits.",
	/** Open Graph locale. */
	locale: "en_US",
	/** ISO language for <html> / feeds. */
	language: "en",
	/** Twitter/X handle including the leading "@", or "" to omit. */
	twitterHandle: "",
	author: "Civic Sins",
	/** The person behind the project (used for attribution + JSON-LD). */
	maker: "Gopal Khadka",
	/** First public year — drives the footer copyright line. */
	foundingYear: 2026,
	/**
	 * Default social-share image (site-relative). Generated by scripts/generate-og.ts.
	 * Per-comic pages override this with their own `/og/<slug>.png` card.
	 */
	defaultOgImage: "/og/default.png",
} as const;
